### ISSUE TITLE
Could you please give us examples with actual working keys ?

### ISSUE THREAD

**Issue by Tenclea** [IvanAdmaers/captcha-verifer#1]
It would be great to have some examples with real-life tested keys in order to be able to llearn how to use your package and how to find the different parts required (like token and superKey)

**Comment by IvanAdmaers** [comment]
Hello. Thank you for your interest to this package. I’m going to update this package and add some additional features. I also add more detailed README with real examples.

**Comment by IvanAdmaers** [comment]
I have sketched a simple example of working with a package.
<img width="619" alt="success" src="https://user-images.githubusercontent.com/66776981/109623902-120ac900-7b57-11eb-810c-e2f8a39d13ed.png">
[test.zip](https://github.com/IvanAdmaers/captcha-verifer/files/6067385/test.zip)
